### ISSUE TITLE
PR this into RS?

### ISSUE THREAD

**Issue by raoulvdberge** [thraaawn/ocrsdriver#1]
Hi,

I was busy working on a OC driver for RS myself, until I saw yours, which has more features than what I had already.

I figured it'd be a waste of time to work on a driver myself when you wrote already one.

I was wondering if you were able to PR this into RS itself? The OC API is already included.

Thanks

Raoul

**Comment by davenonymous** [comment]
Sure, I'll look into it. Might take a few days though as I usually only have time to work on mods on the weekend.

**Comment by raoulvdberge** [comment]
Cool. If you want, I can also copy / paste your code myself. I would modify it a bit so it is 1.11 compatible, which is the target branch. Obviously, you'd still get the credits for it.

But if you'd rather PR, I understand that.

**Comment by davenonymous** [comment]
Feel free to copy+paste, I don't mind at all!

A few things from the top of my head that would need to be improved before releasing this upstream though:
- There are a few npe's still in there, that I did not get around to fixing, yet :( As you certainly know, there might not be a network for getNetwork() to return.
- The implementation currently targets INetworkNode, which is way to general for some of the OC methods provided, i.e. you can currently extract stuff from cables.
- Item comparison functionality should be added to some methods, i.e. your IComparer interface is only used for getItem(), but really should also be used in extractItem() and usable from lua in cancelCrafting() etc

**Comment by raoulvdberge** [comment]
Those are some things I saw, I'll improve them. Thanks!

**Comment by raoulvdberge** [comment]
https://github.com/raoulvdberge/refinedstorage/commit/8bf60fd06a40763eb0736daf6fde91e9ffa25517

Thanks!

(Still needs some changes regarding the IComparer flags)
